use crate::types::{StateId, ObjectId, LinkType};
use crate::types::AbortReason;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Opcode {
    Read,
    Write,
    Effect,
    ObjectBirth,
    ObjectDeath,
    Trap,
    HostCall,
    ObjectFreeze,
    ObjectLink,
    ObjectUnlink,
    CapabilityGrant,
    Savepoint,
    RollbackTo,
    LoadConst,
    Add,
    Sub,
    Cmp,
    LoadStateU64,
    LoadStateBytes,
    WriteRegister,
    Jmp,
    Jz,
    Jnz,
    Nop,
    Halt,
    Jn,
    Commit,
    Abort,
    Call,
    Return,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Instruction {
    Read { state_id: StateId },
    Write { state_id: StateId, payload: Vec<u8> },
    Effect { payload: Vec<u8> },
    ObjectBirth { object_id: ObjectId },
    ObjectDeath { object_id: ObjectId },
    Trap { service_id: u8 },
    HostCall { call_id: u8 },
    ObjectFreeze { object_id: ObjectId },
    ObjectLink { from: ObjectId, to: ObjectId, relation: LinkType },
    ObjectUnlink { from: ObjectId, to: ObjectId },
    CapabilityGrant { holder: ObjectId, permission: String, resource: StateId },
    Savepoint { name: String },
    RollbackTo { name: String },
    /// 切换当前执行上下文到目标Object，跳转到entry_pc继续执行。
    /// 对应module.md第6节"跨Module调用"设计的最小可用实现：
    /// 暂不涉及独立代码空间，仅切换current_object + 维护调用栈。
    Call { object_id: ObjectId, entry_pc: usize },
    /// 从Call返回：恢复调用前的current_object和pc。
    Return,
    Nop,
    LoadConst { reg: u8, val: u64 },
    Add { dst: u8, src1: u8, src2: u8 },
    Sub { dst: u8, src1: u8, src2: u8 },
    Cmp { src1: u8, src2: u8 },
    LoadStateU64 { reg: u8, state_id: StateId },
    LoadStateBytes { reg: u8, state_id: StateId },
    WriteRegister { state_id: StateId, reg: u8 },
    Jmp { target: usize },
    Jz { target: usize },
    Jnz { target: usize },
    Jn { target: usize },
    Halt,
    Commit,
    Abort { reason: AbortReason },
}

impl Instruction {
    pub fn opcode(&self) -> Opcode {
        match self {
            Instruction::Read { .. } => Opcode::Read,
            Instruction::Write { .. } => Opcode::Write,
            Instruction::Effect { .. } => Opcode::Effect,
            Instruction::ObjectBirth { .. } => Opcode::ObjectBirth,
            Instruction::ObjectDeath { .. } => Opcode::ObjectDeath,
            Instruction::Trap { .. } => Opcode::Trap,
            Instruction::HostCall { .. } => Opcode::HostCall,
            Instruction::ObjectFreeze { .. } => Opcode::ObjectFreeze,
            Instruction::ObjectLink { .. } => Opcode::ObjectLink,
            Instruction::ObjectUnlink { .. } => Opcode::ObjectUnlink,
            Instruction::CapabilityGrant { .. } => Opcode::CapabilityGrant,
            Instruction::Savepoint { .. } => Opcode::Savepoint,
            Instruction::RollbackTo { .. } => Opcode::RollbackTo,
            Instruction::Nop => Opcode::Nop,
            Instruction::Halt => Opcode::Halt,
            Instruction::LoadConst { .. } => Opcode::LoadConst,
            Instruction::Add { .. } => Opcode::Add,
            Instruction::Sub { .. } => Opcode::Sub,
            Instruction::Cmp { .. } => Opcode::Cmp,
            Instruction::LoadStateU64 { .. } => Opcode::LoadStateU64,
            Instruction::LoadStateBytes { .. } => Opcode::LoadStateBytes,
            Instruction::WriteRegister { .. } => Opcode::WriteRegister,
            Instruction::Jmp { .. } => Opcode::Jmp,
            Instruction::Jz { .. } => Opcode::Jz,
            Instruction::Jnz { .. } => Opcode::Jnz,
            Instruction::Jn { .. } => Opcode::Jn,
            Instruction::Commit => Opcode::Commit,
            Instruction::Abort { .. } => Opcode::Abort,
            Instruction::Call { .. } => Opcode::Call,
            Instruction::Return => Opcode::Return,
        }
    }
}
